apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dice-roller
  description: It rolls dice
  tags:
    - go
  annotations:
    'backstage.io/kubernetes-id': dice-roller
    'backstage.io/kubernetes-namespace': dtf-dev-nimbus-fwrkdev
spec:
  type: service
  lifecycle: production
  owner: user:guest 
  system: examples
